# Generated by Django 4.0.4 on 2023-02-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
